FROM node:20-alpine AS builder

WORKDIR /app

COPY Frontend/package*.json ./
RUN npm install

COPY Frontend ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/src/assets /usr/share/nginx/html/src/assets
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]