# Generated by Django 4.2.18 on 2026-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0003_folder_is_root_folder_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
