# Generated by Django 4.2.18 on 2026-04-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_alter_folder_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_root', True)), fields=('user',), name='unique_root_folder_per_user'),
        ),
    ]
