# Generated by Django 4.2.18 on 2026-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscriptionplan_can_access_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='upload_limit_mb',
            field=models.IntegerField(default=5),
        ),
    ]
