# Generated by Django 4.2.18 on 2026-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscriptionplan_upload_limit_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_lifetime',
            field=models.BooleanField(default=False),
        ),
    ]
