# Generated by Django 4.2.18 on 2026-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
