# Generated by Django 4.2.18 on 2026-06-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_subscriptionplan_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_set_access_limit',
            field=models.BooleanField(default=False, help_text='Allow setting max unique user access limit'),
        ),
    ]
