# Generated by Django 4.2.18 on 2026-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
