# Generated by Django 4.2.18 on 2026-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scan_visitor_email_scan_visitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='visitor_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
