# Generated by Django 4.2.18 on 2026-04-21 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrcodes', '0010_alter_qrcode_created_at_alter_qrcode_short_slug_and_more'),
        ('scans', '0003_alter_scan_country_alter_scan_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scan',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_records', to='qrcodes.qrcode'),
        ),
    ]
