# Generated by Django 4.2.18 on 2026-03-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0003_alter_qrcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='short_slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
