# Generated by Django 4.2.18 on 2026-03-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_alter_folder_id'),
        ('qrcodes', '0004_qrcode_short_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='folders.folder'),
        ),
    ]
