# Generated by Django 4.2.18 on 2026-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0005_alter_qrcode_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_lead_capture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
