# Generated by Django 4.2.18 on 2026-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0006_qrcode_is_lead_capture_qrcode_is_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='show_preview',
            field=models.BooleanField(default=True),
        ),
    ]
