# Generated by Django 4.2.18 on 2026-03-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0008_alter_qrcode_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
