# Generated by Django 4.2.18 on 2026-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0009_qrcode_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='short_slug',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['user', 'status'], name='qrcodes_qrc_user_id_1671eb_idx'),
        ),
    ]
