# Generated by Django 4.2.18 on 2026-05-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0010_alter_qrcode_created_at_alter_qrcode_short_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatekeeperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('pdf', 'PDF'), ('business', 'Business'), ('file', 'File'), ('default', 'Default')], max_length=50, unique=True)),
                ('password_enabled', models.BooleanField(default=True, help_text='Allow password protection for this category')),
                ('lead_capture_enabled', models.BooleanField(default=True, help_text='Allow lead capture for this category')),
                ('timer_enabled', models.BooleanField(default=False, help_text='Auto-redirect timer for categories without a button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gatekeeper Config',
                'verbose_name_plural': 'Gatekeeper Configs',
            },
        ),
    ]
