# Generated by Django 4.2.18 on 2026-06-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0011_gatekeeperconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='max_access_count',
            field=models.IntegerField(blank=True, help_text='Max unique users who can access (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='unique_access_count',
            field=models.IntegerField(default=0, help_text='Current unique access count (atomic)'),
        ),
        migrations.CreateModel(
            name='QRAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='qrcodes.qrcode')),
            ],
            options={
                'verbose_name': 'QR Access',
                'verbose_name_plural': 'QR Access Log',
                'unique_together': {('qr_code', 'ip_address')},
            },
        ),
    ]
