# Generated by Django 4.2.18 on 2026-06-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0012_add_access_limit_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qraccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qraccess',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
